name: Check package managers
on: [pull_request]
jobs:
  check_cocoapods:
    name: Check CocoaPods
    runs-on: macOS-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Install CocoaPod dependencies
        run: pod install
      - name: Run pod lib lint
        run: pod lib lint --allow-warnings
  check_carthage:
    name: Check Carthage
    runs-on: macOS-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Use Xcode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Remove SPMTest
        run: rm -rf SampleApps/SPMTest && git add . && git commit -m 'Remove SPMTest app to avoid Carthage timeout'
      - name: Carthage build
        run: carthage build --no-skip-current
