name: CI
on: [pull_request]
jobs:
  env:
    DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
  unit_test_job:
    name: Unit Tests
    runs-on: macOS-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install CocoaPod dependencies
        run: pod install
      - name: Run Unit Tests
        run: set -o pipefail && xcodebuild -workspace 'Braintree.xcworkspace' -sdk 'iphonesimulator' -configuration 'Debug' -scheme 'UnitTests' -destination 'name=iPhone 11,platform=iOS Simulator'  test  | ./Pods/xcbeautify/xcbeautify
  ui_test_job:
    name: UI Tests
    runs-on: macOS-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install CocoaPod dependencies
        run: pod install
      - name: Run UI Tests
        run: set -o pipefail && xcodebuild -workspace 'Braintree.xcworkspace' -sdk 'iphonesimulator' -configuration 'Release' -scheme 'UITests' -destination 'name=iPhone 11,platform=iOS Simulator'  test  | ./Pods/xcbeautify/xcbeautify
  integration_test_job:
    name: Integration Tests
    runs-on: macOS-latest
    steps:
      # Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install CocoaPod dependencies
        run: pod install
      - name: Run Integration Tests
        run: set -o pipefail && xcodebuild -workspace 'Braintree.xcworkspace' -sdk 'iphonesimulator' -configuration 'Release' -scheme 'IntegrationTests' -destination 'name=iPhone 11,platform=iOS Simulator'  test  | ./Pods/xcbeautify/xcbeautify